### ISSUE TITLE
Error on Cronjob

### ISSUE THREAD

**Issue by BembelGmbH** [PAYONE-GmbH/magento-1#148] opened 2018-01-16 09:23 UTC
- Magentoversion: 1.9.3.1
- Pluginversion: 3.7.8

Hi,
we have an error @ payone Cronjob:  TRIGGER: shutdown function
![firefox_2018-01-16_10-16-41](https://user-images.githubusercontent.com/20416429/34981083-b47abae0-faa6-11e7-8e5a-1da5a3281ec2.png)
Nothing about it in the payone_cron.log: 
```
2018-01-16T09:13:02+00:00 INFO (6): Started cronjob
2018-01-16T09:13:02+00:00 INFO (6): executePending: finished 0
2018-01-16T09:13:02+00:00 INFO (6): Finished cronjob
2018-01-16T09:14:02+00:00 INFO (6): Started cronjob
2018-01-16T09:14:02+00:00 INFO (6): ID: 16 - Execute - Execute TransactionStatus action: appointed - store-id: 2
2018-01-16T09:14:02+00:00 INFO (6): ID: 16 - Execute - Set status to running
2018-01-16T09:14:02+00:00 INFO (6): ID: 16 - Process - Got order id: 98 store-id: 2
2018-01-16T09:14:02+00:00 INFO (6): ID: 16 - Process - Update TransactionStatus
2018-01-16T09:14:02+00:00 INFO (6): ID: 16 - Process - Update order status
2018-01-16T09:14:02+00:00 INFO (6): ID: 16 - Process - Add order comment
2018-01-16T09:14:02+00:00 INFO (6): ID: 16 - Process - Store clearing parameters
2018-01-16T09:14:02+00:00 INFO (6): ID: 16 - Process - Save before events
2018-01-16T09:14:02+00:00 INFO (6): ID: 16 - Process - Trigger event payone_core_transactionstatus_all
2018-01-16T09:14:02+00:00 INFO (6): ID: 16 - Process - Trigger event payone_core_transactionstatus_appointed

```
Also nothing in the php or nginx logs-

It happend on one Transaktion until now. The Tranaktionsstatus stays "running" - we can reproduce the error by changing the column "processing_status" to "pending" in the DB .

What might be the cause?
thanks

**Comment by fjbender** [comment] 2018-01-16 09:45
@BembelGmbH This might be a duplicate of #119

**Comment by BembelGmbH** [comment] 2018-01-16 11:55
The error seems to occur when the order contains special characters, like öäüß and so on

**Comment by fjbender** [comment] 2018-01-16 12:49
I couldn't reproduce this with öäüß in neither street nor name fields on magento 1.9.3.1 with the current master.

**Closed** 2022-02-11 08:34 UTC
Labels: help wanted
