### ISSUE TITLE
Missing payolution.js when quote is not available

### ISSUE THREAD

**Issue by JEreth** [PAYONE-GmbH/magento-1#360] opened 2019-08-08 14:45 UTC
It seems like the payolution.js from the additional script is not loaded when no quote exists (i.e. a guest users opens the checkout page for the first time and has not yet entered any data).

The issue is probably somewhere here in the model Mage_Payment_Model_Method_Abstract and the method isAvailable. The payolution availability check probably checks for additional information like name, gender, street, age and so on.

Workaround:
We haven't examined the issue further and just hard coded the include of the payolution.js

**Comment by fjbender** [comment] 2019-08-13 12:15
We'll check this out.

**Comment by Anton-Levitsky** [comment] 2020-01-03 07:22
Hi @JEreth, I have checked the issue and was not able to reproduce the Bug. 
Can you please provide me with more information? Ho do you know, that payolution.js is not loaded? 

Also, as I can see the payolution availability check does not check for customer specific information.

**Comment by hreinberger** [comment] 2020-02-05 12:13
We're closing this for now - if you have any more info, feel free to reopen.

**Closed by hreinberger** 2020-02-05 12:13 UTC
