### ISSUE TITLE
Amazon Pay broken in Facebook Browser

### ISSUE THREAD

**Issue by gndk** [PAYONE-GmbH/magento-1#358] opened 2019-07-27 18:39 UTC
Amazon Pay is again broken in the Facebook browser.

See https://screencast.com/t/1Rb0ceYU
And https://screencast.com/t/c0nTRQXOXR

According to https://pay.amazon.de/help/202030010 Facebook browser is supported on iOs 12.2+, which I have.

Maybe you can contact Amazon and ask them WTF is going on, because this is costing us A LOT of money.

Payone Master 3669176
Magento 1.9.4.1
iPhone 7
iOs 12.3.1
Facebook App Version 231.0 (latest as of 29.07.)

**Comment by hreinberger** [comment] 2019-07-29 07:37
Hi @gndk 
I tried to reproduce this issue on mobile safari, since my understanding was that all In App Browsers on iOS use Safari as their rendering engine, but Amazon Pay worked as expected. Maybe Amazon blocks the user agent of the facebook in-app browser. 
Could you give me the steps to reproduce this? I'll then have a closer look.

**Comment by gndk** [comment] 2019-07-29 13:25
Amazon lists Mobile Safari and mobile FB browser separately, so I guess they look at the user agent differently.

For me the steps to reproduce are:
Visit site in mobile safari -> Amazon Pay works
Visit site in FB inapp browser -> Error from my screenshot

I dont think its possible to type in any url into the FB inapp browser. As a workaround you could post a link to your test site as a status update and set privacy to "just me", then click the link in the fb post to open it in the inapp browser.

**Comment by gndk** [comment] 2019-07-29 13:28
I had to disable the Amazon Pay button for the Inapp user agents now 😭 💸  

`<?php if(strpos($_SERVER['HTTP_USER_AGENT'], 'FBAN/') === false && strpos($_SERVER['HTTP_X_REQUESTED_WITH'], 'com.facebook.') === false): ?>`

**Comment by gndk** [comment] 2019-07-29 13:39
Still works on Android. Only iOs causing problems. Don't know since when.

I have a support ticket with Amazon Pay support, too, but didn't hear anything back yet.

**Comment by hreinberger** [comment] 2019-07-29 13:59
Thanks for the tip regarding posting a link only to me.
Prerequisites:

- iPhone Xs, iOS 12.4
- Magento 1.9.4.2, PAYONE Master, letsencrypt cert
- Default amazon config in backend

So then I:
1. installed the latest facebook app
2. opened my link in the in-app browser
3. logged in using my amazon test account
4. could finish the order as expected.

I'm not sure where to search for the culprit here. Could be my newer Magento or iOS version. To me this looks as expected though

**Comment by hreinberger** [comment] 2019-07-29 14:11
oops didn't mean to. Feel free to add more info or close this one yourself

**Comment by gndk** [comment] 2019-07-29 14:43
Hm. I'll upgrade to iOs 12.4 and see if it fixes it. But Amazon lists 12.2+ as supported. Can't really expect users to be on the bleeding edge version of software just to have something as basic as an online payment working...

**Comment by gndk** [comment] 2019-07-29 18:43
Works again on iOs 12.4. Seems like Amazon no longer supports anything else but the latest version, but doesn't deem it necessary to inform its customers about it. Wankers.

**Closed** 2019-07-29 18:43 UTC
