### ISSUE TITLE
Klarna Invoicing select, in frontend "Klarna Base" is getting used

### ISSUE THREAD

**Issue by luckyduck** [PAYONE-GmbH/magento-1#453] opened 2020-10-30 13:52 UTC
We had to update to 5.0.0 from an earlier version. 

I was able to add the method "klarna_invoicing" in the backend. However, in the frontend, this leads to "Klarna based being used.

First symptom I noticed was, that the configured name "Rechnung ..." was not used. Instead the frontend showed "Payone - Klarna". 

In addition, the payment[method] in checkout is payone_klarna_base as well. 

The result is, that the payment method is not accepted when you try to checkout. 

Any help or pointers are more than appreciated!

**Comment by T-Kuchel** [comment] 2020-11-02 10:44
Hello @luckyduck ,

klarna_inoving is obsolete and should no longer be used.
This is currently only included to allow migration.

A turn to the new methods is the best way.
In the long run klarna_invoicing will also disappear.

Greetings from Kiel

**Comment by luckyduck** [comment] 2020-11-02 11:22
But "klarna_invoicing" is what your technical support told me to use over the phone. I talked to them 3 times last week and spent like 2,5 days searching.

What should we use instead?

**Comment by luckyduck** [comment] 2020-11-02 11:22
In the past, the customer used safe_invoice, which is not active in the account any longer, I was told.

**Comment by alexanderbug** [comment] 2020-11-05 14:49
Have the new Klarna access data for the interface been transferred to Payone?

We have the problem that our new accounts have not yet been activated by Klarna. This causes the message Incorrect configuration to be displayed.

We had many problems here, which were caused by Klarna itself and not by the Payone integration

**Comment by luckyduck** [comment] 2020-11-05 14:55
@alexanderbug I will check that. Thank you for that hint. I just got handed the informations / credentials.

**Comment by alexanderbug** [comment] 2020-11-05 15:01
In the old interface the IDs would be entered directly in the module. In the new one Payone has to store the data.

**Comment by fjbender** [comment] 2020-11-05 15:40
That might actually be the issue, thank you @alexanderbug.

@luckyduck please contact our Merchant Service to confirm that your Klarna credentials have been set up correctly

**Comment by luckyduck** [comment] 2020-11-05 15:57
@fjbender That I checked already. They told me last week, that Klarna is entered in your system. However: I just asked my customer to get in touch with Klarna, if the account is really already approved/active/live.

**Comment by fjbender** [comment] 2020-11-06 08:42
All right, thanks. Could you also please send over the merchant ID and a staging shop instance URL (if available) to integrations@payone.com?

**Comment by luckyduck** [comment] 2020-11-06 08:54
@fjbender Thank you very much! You got mail :)

**Closed** 2024-10-01 08:21 UTC
