### ISSUE TITLE
User Role Permissions for Logs -> Transactionstatus -> View/Export are not saved

### ISSUE THREAD

**Issue by gndk** [PAYONE-GmbH/magento-1#51] opened 2017-03-11 20:56 UTC
To reproduce change user role resource access to custom, enable payone logs -> transactionstatus -> view/export and save role. After opening the resource access settings for this user role again those 2 permissions are disabled again.

**Comment by T-Kuchel** [comment] 2017-03-14 13:59
Sorry but i can't reproduce that issue on our instances. We are using version 1.9.3.2 with the master of the extension.

**Comment by gndk** [comment] 2017-03-14 14:05
I'm using 1.9.3.2 with Release v3.7.6.

Just checked again and its still there, see short video here: https://www.screencast.com/t/2EaQ6GvYS

Maybe you already fixed it since release 3.7.6

**Comment by T-Kuchel** [comment] 2017-03-16 10:55
OK. Now i can reproduce... @FATCHIP-GmbH please have a look.

**Comment by T-Kuchel** [comment] 2017-03-17 11:31
fixed with https://github.com/PAYONE-GmbH/magento-1/issues/54

**Closed** 2017-03-17 11:31 UTC
