### ISSUE TITLE
Payment method configuration for method "payone_online_bank_transfer" not found

### ISSUE THREAD

**Issue by hardiklinksture** [PAYONE-GmbH/magento-1#236] opened 2018-07-23 11:04 UTC
Hello,
Recently i upgrade magento version 1.7.0.2 to 1.9.3.9 and latest version of payone (4.1.7)
But POSTFINANCE payment method not working on magento default check and onestepcheckout.

If i checkout with default magento then generate below report.

```
a:5:{i:0;s:80:"Payment method configuration for method "payone_online_bank_transfer" not found.";i:1;s:4722:"#0 /app/code/community/Payone/Core/Block/Payment/Method/Info/Abstract.php(59): Payone_Core_Helper_Config->getConfigPaymentMethodByQuote(Object(Idev_OneStepCheckout_Model_Sales_Quote))
#1 /app/code/community/Payone/Core/Block/Payment/Method/Info/Abstract.php(79): Payone_Core_Block_Payment_Method_Info_Abstract->getPaymentConfig()
#2 /app/design/frontend/default/gesund_gekauft/template/payone/core/payment/method/info/onlinebanktransfer.phtml(26): Payone_Core_Block_Payment_Method_Info_Abstract->getMethodTitle()
#3 /app/code/core/Mage/Core/Block/Template.php(241): include('/media/jaguar/s...')
#4 /app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/defaul...')
#5 /app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#6 /app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Template->_toHtml()
#7 /app/code/core/Mage/Checkout/Block/Onepage/Payment/Info.php(54): Mage_Core_Block_Abstract->toHtml()
#8 /app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Checkout_Block_Onepage_Payment_Info->_toHtml()
#9 /app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
#10 /app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml('payment_info', true)
#11 /app/code/core/Mage/Checkout/Block/Onepage/Progress.php(69): Mage_Core_Block_Abstract->getChildHtml('payment_info')
#12 /app/design/frontend/base/default/template/checkout/onepage/progress/payment.phtml(34): Mage_Checkout_Block_Onepage_Progress->getPaymentHtml()
#13 /app/code/core/Mage/Core/Block/Template.php(241): include('/media/jaguar/s...')
#14 /app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/base/d...')
#15 /app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#16 /app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Template->_toHtml()
#17 /app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#18 /app/code/core/Mage/Checkout/controllers/OnepageController.php(243): Mage_Core_Model_Layout->getOutput()
#19 /app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->progressAction()
#20 /app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('progress')
#21 /app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#22 /app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#23 /app/Mage.php(683): Mage_Core_Model_App->run(Array)
#24 /index.php(95): Mage::run('', 'store')
#25 {main}";s:3:"url";s:90:"/magento-m1/gesund-gekauft.ch/project-upgraded/checkout/onepage/progress/?prevStep=payment";s:11:"script_name";s:56:"/magento-m1/gesund-gekauft.ch/project-upgraded/index.php";s:4:"skin";s:7:"default";}
```

Thanks in advance.

**Comment by fjbender** [comment] 2018-07-23 12:25
This seems to be a duplicate of #8.

However, especially when upgrading, our Technical Support Team can walk you through several workaround steps, e.g. re-creating all payment method configurations within the plugin. Please contact them first for detailed help.

Thanks
Florian

**Comment by hardiklinksture** [comment] 2018-07-25 06:18
i check the #8 and i delete old payment method and creating new but i can not find "online_bank_transfer" payment method in new version can you please check my old version screen shot i can see the online_bank_transfer : https://prnt.sc/kaoryx but i can not see in new version please check screen shot : https://prnt.sc/kaos8j

**Comment by fjbender** [comment] 2018-07-25 07:21
The `online_bank_transfer` payment method was split up in individual payment methods like `online_bank_transfer_sofort` for Sofort Überweisung. Please use the individual buttons for Sofort, Post Finance, etc. to add individual online bank transfer payment methods.

**Comment by hardiklinksture** [comment] 2018-07-26 12:38
I have enabled `New PostFinance E-Finance` and `New PostFinance Card` on our test site with test mode but we are getting an error as below.

<pre>[924: Test mode not available] - Konfigurationsproblem. Bitte verwenden Sie eine andere Zahlungsweise.</pre>

Please check this https://prnt.sc/kbai9c screenshot for more information and let us know how can we test both payment method with test mode?

**Comment by fjbender** [comment] 2018-07-26 13:19
Please contact our support team for this, they are able to set you up with a test mode connection to PostFinance.

There is no issue in the module here, so I'll close this.

**Closed by fjbender** 2018-07-26 13:19 UTC
