### ISSUE TITLE
PayPal Orders Are Sometimes Saved as Prepayment Orders

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#35] opened 2017-02-16 16:32 UTC
Magento 1.9.2.4, PAYONE 3.7.3.

Most of the PayPal orders are correctly shown as "PayPal" in the backend. Unfortunately, some orders, which have been paid via PayPal are shown as "Prepayment" / "Vorkasse". The `payment_method` in this case is still `payone_wallet` (=PayPal), but if I go into the order, under "Payment Information" / "Zahlungsinformation", the value "Prepayment" / "Vorkasse" is shown. Any idea how this happens?

The PAYONE support could not reproduce the issue (which I understand as it is rare), but this may not happen at all I think.

**Comment by FatchipRobert** [comment] 2017-02-20 13:20
The only way we could reproduce this behaviour by now is with a kind of "tabbed-fraud" approach with having one tab of the shop go to PayPal Express and having another tab of the shop going through the checkout and changing the payment type to prepayment for example and then finishing the checkout in the PayPal Express tab.

Is PayPal Express activated in your shop?

**Comment by sprankhub** [comment] 2017-02-20 13:59
PayPal Express is not activated, no. Only PayPal via PAYONE is activated.

**Comment by sprankhub** [comment] 2017-03-09 13:59
Any update? Any idea? Anything we could check?

**Comment by FatchipRobert** [comment] 2017-03-09 14:27
Unfortunately I didn't find a way to reproduce this behaviour yet.

**Comment by isronny** [comment] 2017-03-10 10:34
Hi - we have the same problems. Most orders with paypal express are OK . But in a few orders there is the information "Lastschrift" or "Ratenkauf" (other payment options in our shop). On the overview there are the correct information, in order details are the information sometimes wrong.

**Comment by tniebergall** [comment] 2017-07-06 07:13
Hi,

do you use a delete order module in these projects or migrated any kind of data?
We had a similar case on one of our staging systems, were the order tables where cleaned but the payone tables stayed untouched.

**Comment by sprankhub** [comment] 2017-07-06 07:20
No migration and no order deletion - at least not since one or two years. Maybe orders have been deleted before - not sure about that. Could that still be the reason? What would I need to check? Thanks!

**Comment by tniebergall** [comment] 2017-08-04 09:46
Know we have the same behavior for some orders the method is set to payone_wallet_paypal_express but the payone_config_payment_method_id points to the wrong configuration.

You can get the affected orders with the following query. You have to set your Ids for the paypal config from payone_config_payment_method

`SELECT * FROM `sales_flat_order_payment` WHERE `method` LIKE 'payone_wallet_paypal_express' AND `payone_config_payment_method_id` NOT BETWEEN 77 AND 80`

**Comment by sprankhub** [comment] 2017-09-20 07:15
This is exactly my issue @tniebergall. I have 2033 (!) such weird payments in the database. This really needs to be solved. The issue is even worse, because it seems that the payment updates are not correctly transferred to the shop then.

**Comment by riconeitzel** [comment] 2017-09-27 10:31
we do have this issue as well … but no order deletion or migration system (not that we are aware of).

**Comment by riconeitzel** [comment] 2017-10-05 12:50
any news here? @tniebergall @sprankhub @FatchipRobert

**Comment by Celldweller** [comment] 2017-10-06 09:34
We do have this issue as well. Orders which were paid by Paypal are marked as Cash on Delivery and - to make things worse - CoD charge is added too.

**Comment by tniebergall** [comment] 2017-10-06 09:59
We've this issue as well and I'm in the process of finding a case to reproduce this issue. @riconeitzel  and @Celldweller could you execute this  [query](https://github.com/PAYONE-GmbH/magento-1/issues/35#issuecomment-320207160) an send me the percentage of affected orders related to all orders?

**Comment by riconeitzel** [comment] 2017-10-06 10:05
```sql
SELECT count(*) AS qty, method, payone_config_payment_method_id as config_id  FROM sales_flat_order_payment GROUP BY method;
```

qty|method|config_id
--|--|--
754|payone_creditcard|3
272|payone_online_bank_transfer|7
18|payone_online_bank_transfer_sofortueberweisung|15
5|payone_safe_invoice|11


Your query as is will return 0 rows.

**Comment by tniebergall** [comment] 2017-10-06 10:19
Then we have multiple issues here. My query collects orders where the config id an method differ for paypal. 
Does you query show all available methods? Because paypal is missing.

**Comment by Celldweller** [comment] 2017-10-06 11:35
method | config_id
--------- | ------
payone_advance_payment | 6
payone_cash_on_delivery | 9
payone_creditcard | 12
payone_debit_payment | 15
payone_wallet | 3

The query would not get a result for me as well like @riconeitzel . Here are my `config_id` values and the methods we use. Paypal is `payone_wallet`

**Comment by tniebergall** [comment] 2017-10-06 11:38
@Celldweller which magento and payone version is installed in your store?

**Comment by riconeitzel** [comment] 2017-10-06 11:59
qty|method|config_id
--|--|--
426|bankpayment|0
1|checkmo|0
44|free|0
754|payone_creditcard|3
272|payone_online_bank_transfer|7
18|payone_online_bank_transfer_sofortueberweisung|15
5|payone_safe_invoice|11
118|payonpickup|0
2606|paypal_express|0
141|phoenix_cashondelivery|0
113|vaimo_klarna_invoice|0

Here are all payment methods @tniebergall

**Comment by Celldweller** [comment] 2017-10-06 14:11
Magento CE 1.9.3.1 and Payone 3.7.8

**Comment by sprankhub** [comment] 2018-03-23 07:48
Status?

**Comment by axe1987** [comment] 2019-08-02 11:24
Is there an Update for this issue.
We have the same Problem with Paypal express and giropay in the order details.

greets
axe1987

**Closed** 2022-02-10 12:52 UTC
Labels: bug
