### ISSUE TITLE
"Die angeforderte Zahlungsart ist nicht verfügbar" Exception in the Checkout

### ISSUE THREAD

**Issue by rafallmmw** [PAYONE-GmbH/magento-1#171] opened 2018-03-01 14:17 UTC
In Checkout > Billing address: when I click "Continue" (as a Guest user) then I'm landing in the shopping cart. 
There is following exception in logs:

a:5:{i:0;s:50:"Die angeforderte Zahlungsart ist nicht verfügbar.";i:1;s:3057:"#0 /var/www/kd/stage.inwerk.de/app/code/core/Mage/Payment/Model/Info.php(82): Mage::throwException('Die angefordert...')
#1 /var/www/kd/stage.inwerk.de/app/code/core/Mage/Sales/Model/Quote/Payment.php(218): Mage_Payment_Model_Info->getMethodInstance()
#2 /var/www/kd/stage.inwerk.de/app/code/community/Payone/Core/Block/Checkout/Onepage/Payment/Methods.php(151): Mage_Sales_Model_Quote_Payment->getMethodInstance()
#3 /var/www/kd/stage.inwerk.de/app/design/frontend/enterprise/inwerk/template/checkout/onepage/payment/methods.phtml(18): Payone_Core_Block_Checkout_Onepage_Payment_Methods->getSelectedMethodCode()
#4 /var/www/kd/stage.inwerk.de/app/code/core/Mage/Core/Block/Template.php(241): include('/var/www/kd/sta...')
#5 /var/www/kd/stage.inwerk.de/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/enterp...')
#6 /var/www/kd/stage.inwerk.de/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#7 /var/www/kd/stage.inwerk.de/app/code/core/Mage/Core/Block/Abstract.php(890): Mage_Core_Block_Template->_toHtml()
#8 /var/www/kd/stage.inwerk.de/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#9 /var/www/kd/stage.inwerk.de/app/code/local/Mediawave/Dropshipping/Model/Observer.php(490): Mage_Core_Model_Layout->getOutput()
#10 /var/www/kd/stage.inwerk.de/app/code/local/Mediawave/Dropshipping/Model/Observer.php(472): Mediawave_Dropshipping_Model_Observer->_getPaymentMethodsHtml()
#11 /var/www/kd/stage.inwerk.de/app/code/core/Mage/Core/Model/App.php(1339): Mediawave_Dropshipping_Model_Observer->saveCheckoutAddresses(Object(Varien_Event_Observer))
#12 /var/www/kd/stage.inwerk.de/app/code/core/Mage/Core/Model/App.php(1318): Mage_Core_Model_App->_callObserverMethod(Object(Mediawave_Dropshipping_Model_Observer), 'saveCheckoutAdd...', Object(Varien_Event_Observer))
#13 /var/www/kd/stage.inwerk.de/app/Mage.php(447): Mage_Core_Model_App->dispatchEvent('controller_acti...', Array)
#14 /var/www/kd/stage.inwerk.de/app/code/core/Mage/Core/Controller/Varien/Action.php(546): Mage::dispatchEvent('controller_acti...', Array)
#15 /var/www/kd/stage.inwerk.de/app/code/core/Mage/Core/Controller/Front/Action.php(80): Mage_Core_Controller_Varien_Action->postDispatch()
#16 /var/www/kd/stage.inwerk.de/app/code/core/Mage/Core/Controller/Varien/Action.php(422): Mage_Core_Controller_Front_Action->postDispatch()
#17 /var/www/kd/stage.inwerk.de/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('saveBilling')
#18 /var/www/kd/stage.inwerk.de/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#19 /var/www/kd/stage.inwerk.de/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#20 /var/www/kd/stage.inwerk.de/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#21 /var/www/kd/stage.inwerk.de/index.php(133): Mage::run('bue_de', 'store')
#22 {main}";s:3:"url";s:30:"/checkout/onepage/saveBilling/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:6:"bue_de";}

Module version: 4.1.1

**Comment by tim-bezhashvyly** [comment] 2018-03-08 22:02
+1

Caused by [this code](https://github.com/PAYONE-GmbH/magento-1/blob/master/app/code/community/Payone/Core/Block/Checkout/Onepage/Payment/Methods.php#L186) when quote payment method is NULL.

**Comment by tim-bezhashvyly** [comment] 2018-03-09 07:42
I could provide a PR but in order to do so I need to understand why do you override `getSelectedMethodCode()` method in the first place.

**Comment by sprankhub** [comment] 2018-03-09 07:48
The code has been introduced in https://github.com/PAYONE-GmbH/magento-1/commit/ef42f022b54ca69fbd591b3f2d8891d734399bf6 and attempted to fix #57. #131 may be related as well / may be a duplicate.

**Comment by tim-bezhashvyly** [comment] 2018-03-11 18:28
Yes. Looks like this issue duplicates #131. May be closed.

**Comment by fjbender** [comment] 2018-03-14 07:58
Closed as duplicate of #131

**Closed by fjbender** 2018-03-14 07:58 UTC
